name: Rust

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  container-job:
    runs-on: ubuntu-latest
    container: rustlang/rust:nightly-alpine

    services:
      postgres:
        image: postgres
        env:
          POSTGRES_DB: archivanima
          POSTGRES_USER: archivanima_user
          POSTGRES_PASSWORD: archivanima_password
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
      - name: Check out repository code
        uses: actions/checkout@v3
      - name: Install apk packages
        run: apk add libressl-dev gcc npm libc-dev sassc
      - name: Install npm packages
        run: npm install -g typescript
      - name: Install tools
        uses: baptiste0928/cargo-install@v2
        with:
          crate: sqlx-cli
      - name: Migrate DB
        run: sqlx migrate run
        env:
          DATABASE_URL: 'postgresql://archivanima_user:archivanima_password@postgres:5432/archivanima'
      - name: Build
        run: cargo build --verbose
      - name: Run clippy
        run: cargo clippy --verbose
      - name: Install npm dependencies
        run: npm install
      - name: Connect to PostgreSQL
        run: cargo test --verbose
        env:
          DATABASE_URL: 'postgresql://archivanima_user:archivanima_password@postgres:5432/archivanima'